### ISSUE TITLE
Reminder Form bug

### ISSUE THREAD

**Issue by Samkit-shah** [varadgauthankar/simple_reminder#5]
At time of creating or editing a reminder currently the form only validates whether the title is added or not and if the date and time is not selected still it is being added as a reminder.

**Comment by Samkit-shah** [comment]
Please let me know if I can work on this issue too because if the date is not being added to the hive box then the condition in where statement for the Issue #1 might fail the null check and cause an error.

**Comment by varadgauthankar** [comment]
> At time of creating or editing a reminder currently the form only validates whether the title is added or not and if the date and time is not selected still it is being added as a reminder.
> 

Yes it's on purpose as a reminder need not to be having a end date (or notification) for example adress of a place or phone number.

**Comment by varadgauthankar** [comment]
> Please let me know if I can work on this issue too because if the date is not being added to the hive box then the condition in where statement for the Issue #1 might fail the null check and cause an error.

Only hide the reminders with date

**Comment by Samkit-shah** [comment]
Oh got it,
I will do the changes and update the PR

**Comment by varadgauthankar** [comment]
Closing this issue as it's not a bug
